# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install node and run tests across stable and nightly builds on Windows, Ubuntu and macOS.

name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.5]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}

      - name: Configure node
        run: corepack enable

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint

      - name: Build Check
        run: |
          if [[ -n $(yarn start-ci > /dev/null && git status -s | grep -v '.png') ]]; then
            git status -s
            git diff
            echo "::error title={Build Check}::{'yarn start' must be ran before committing.}"
            exit 1
          else
            exit 0
          fi
